# Generated by Django 5.0.2 on 2024-05-23 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
