# Generated by Django 5.0.2 on 2024-05-23 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="birthday",
        ),
    ]
