# Generated by Django 5.0.2 on 2024-05-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_remove_profile_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="authentication/profile_pics/"
            ),
        ),
    ]
